### ISSUE TITLE
fix: Chips 컴포넌트 수정

### ISSUE THREAD

**Issue by oridori2705** [Programmers-HandsUp/FE-HandsUp#72]
## 배경

- className 추가 가능하게
- 정사각형이 되도록
- 패딩 값이 들어갈 때 일관적이지 않은 부분 수정
![image](https://github.com/Programmers-HandsUp/FE-HandsUp/assets/90139306/7336187e-c259-4c18-ae3a-9ff035f776e4)

## TODO

- [ ] Chips 컴포넌트 더 유연하게가능하도록 수정

## ETC
![표정1](https://github.com/Programmers-HandsUp/FE-HandsUp/assets/90139306/8dbbd02e-2061-45c2-a3c7-e5573a3e6605)
![표정2](https://github.com/Programmers-HandsUp/FE-HandsUp/assets/90139306/d4b70f7a-291e-4141-9c82-43e6f66d39f7)
![표정3](https://github.com/Programmers-HandsUp/FE-HandsUp/assets/90139306/f3e7bda0-f821-4676-a75a-ca574de33788)
![표정4](https://github.com/Programmers-HandsUp/FE-HandsUp/assets/90139306/8f4e8034-0cef-4965-aeea-7f692c468187)
![표정5](https://github.com/Programmers-HandsUp/FE-HandsUp/assets/90139306/b26fa94e-5796-4e2f-8d76-18e1d7020277)
![표정6](https://github.com/Programmers-HandsUp/FE-HandsUp/assets/90139306/6bc22cbb-cfa4-47e5-8bff-381fda1fef4a)

**Comment by hj9118** [comment]
여백이랑 폰트 관련해서도 제안드릴게 있는데
Chip.variants.ts
`"inline-block border rounded-lg px-2 w-full text-center hover:opacity-70 transition-all cursor-pointer",`
현재 코드에서
`px-3 py-1 text-sm`를 넣었을때 UI 비교를 하자면
![image](https://github.com/Programmers-HandsUp/FE-HandsUp/assets/104545906/4df4518c-3cbd-4de6-bcc5-b449ba8ef2af)
\- 적용

![image](https://github.com/Programmers-HandsUp/FE-HandsUp/assets/104545906/d8f356c3-4df9-431b-9c5d-227e07faec45)
\- 미적용

다음과 같은데
text-sm로 위 상품 정보 컴포넌트와 크기가 비슷해 보이는 효과가 있는 것 같아요
(\* 이건 전체 프로젝트에서 비슷한 폰트 사이즈를 유지하는게 좋을 것 같아 한번 의논할 사항이 되겠네요)

그리고 px-2에서 px-3, py-1로 변경할 때도 이미지가 있을 때는 위로도 여백이 생겨 안정감이 느껴지는 것 같고, 하단 멀티체크할때도 사방으로 여백이 있어 일반 라이브러리에서 보는 뱃지, 칩 형태와 조금 더 유사하지 않나 싶네요

텍스트의 경우 className으로 적용하면 될 것 같은데, 패딩 값은 중복 적용이 될 수 있어 화면에 원하는 모습으로 안나올 수 있어 변경하시면서 한번 더 고려해보셨음 싶어 의견드립니다.
